### ISSUE TITLE
Partially obscured Analytics tab

### ISSUE THREAD

**Issue by rbose85** [driftyco/ionic-starter-io#6]
The content of the Analytics tab is partially obscured on iPhone 5, and the page is not scrollable.

![img_0645](https://cloud.githubusercontent.com/assets/2758507/8057330/49f35386-0ea8-11e5-9169-206304ea5245.PNG)

**Comment by patt0** [comment]
http://forum.ionicframework.com/t/quickstart-with-ionic-io-analytics-error/27269

**Comment by Ionitron** [comment]
Greetings @rbose85!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
